import os
import json
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.schema import HumanMessage, SystemMessage

from services.db.reader import (
    get_startup_input,
    get_pipeline_output,
    get_roadmap_profiler,
    get_roadmap_branches,
    get_roadmap_tasks
)

def generate_document_stream(session_id: str, document_type: str):
    """
    Fetches startup context from the database and yields a streaming markdown document.
    Does NOT use AI to prevent 500 API errors and ensure reliable generation.
    """
    # 1. Gather Context
    startup = get_startup_input(session_id)
    if not startup:
        yield "Error: Startup session not found."
        return

    pipeline = get_pipeline_output(session_id)
    profiler = get_roadmap_profiler(session_id)
    branches = get_roadmap_branches(session_id)
    
    tasks = []
    for b in branches:
        tasks.extend(get_roadmap_tasks(b["id"]))

    startup_name = startup.get("startup_name", "Your Startup")
    domain = startup.get("startup_domain", "Unknown Domain")

    doc = f"# {document_type} - {startup_name}\n\n"
    doc += f"**Domain:** {domain}  \n"
    doc += f"**Validation Score:** {pipeline.get('aggregate_validation_score') if pipeline else 'N/A'}/100\n\n"

    doc += "## Executive Summary\n"
    if profiler and profiler.get('reasoning'):
        doc += f"{profiler.get('reasoning')}\n\n"
    else:
        doc += f"A structured {document_type} for {startup_name} operating in the {domain} sector.\n\n"

    doc += "## Startup details\n"
    for key, value in startup.items():
        if key not in ["id", "user_id", "created_at"] and value:
            doc += f"- **{str(key).replace('_', ' ').title()}**: {value}\n"
    
    doc += "\n## Roadmap Pipeline\n\n"
    
    for b in branches:
        doc += f"### {b['branch']}\n"
        doc += f"{b.get('summary', '')}\n\n"
        
        branch_tasks = [t for t in tasks if t.get("branch_id") == b["id"]]
        if branch_tasks:
            doc += "| Task | Phase | Priority | Assigned To |\n"
            doc += "|------|-------|----------|-------------|\n"
            for t in branch_tasks:
                phase = t.get('phase', 'Main')
                priority = t.get('priority', 'Medium')
                assigned = t.get('assigned_to', 'Unassigned')
                doc += f"| **{t['title']}** | {phase} | {priority} | {assigned} |\n"
            doc += "\n"
            
            doc += "#### Task Details\n"
            for t in branch_tasks:
                doc += f"**{t['title']}**\n"
                doc += f"{t.get('description', 'No description provided.')}\n\n"
        
        doc += "---\n\n"

    doc += "## Conclusion\n"
    doc += f"This document was generated by StartupXpert to provide a reliable structured foundation for the team.\n"

    # Simulate streaming by yielding chunks (though it's fast)
    chunk_size = 150
    for i in range(0, len(doc), chunk_size):
        yield doc[i:i+chunk_size]
